services:
  app:
    build: ./app
    container_name: app
    image: app
    hostname: app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --workers 2 --reload --proxy-headers --forwarded-allow-ips=*,
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    env_file:
      - .env
    environment:
      MONGODB_URL: ${MONGODB_URL}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_DB_COLLECTION: ${MONGO_DB_COLLECTION}
      MONGO_USER_USERNAME: ${MONGO_USER_USERNAME}
      MONGO_USER_PASSWORD: ${MONGO_USER_PASSWORD}
    depends_on:
      - mongo
    healthcheck:
      test: curl --fail http://localhost:8000/healthcheck/ || exit 1
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
      - application_network

  mongo:
    image: mongo:latest
    container_name: mongo
    hostname: mongo
    restart: unless-stopped
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongodb-data:/data/db/
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.50'
          memory: 512M
    networks:
      - application_network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    hostname: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
      - application_network


volumes:
  mongodb-data:
    name: mongodb-data


networks:
  application_network:
    name: application_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.5.0/24
          gateway: 172.28.5.1
          aux_addresses:
            app: 172.28.5.20
            mongo: 172.28.5.21
            mongo-express: 172.28.5.22
